version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Empty password for root (optional: NOT recommended for production)
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty passwords (use with caution)
      MYSQL_DATABASE: elearning  # Auto-create a database
      MYSQL_USER: fairus  # Optional: create a guest user
      MYSQL_PASSWORD: "fairus"  # Empty password for the guest user
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
